//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategories
    {
        public int SubcategoryId { get; set; }
        public string SubcategoryName { get; set; }
        public string SubcategoryCode { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
